{
 "title": "Tutorial Environment (Completed)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Rate of Change (Traffic)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(tns_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Change (Traffic)(Grouped by Route)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(tns_request_duration_seconds_count[5m])) by(route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/tns-app.log\"}"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/tns-app.log\"} |= \"error\""
    }
   ]
  }
 ]
}